export const navGroups = [
  { label: "Main", items: ["Overview", "Projects", "Alerts"] },
  { label: "Observability", items: ["Logs"] },
  { label: "Infrastructure", items: ["Servers", "Services", "Docker"] },
  { label: "Delivery", items: ["CI/CD", "Deployments"] },
  { label: "System", items: ["Settings"] },
] as const;

export type ModuleName = (typeof navGroups)[number]["items"][number];

export const pageMeta: Record<
  ModuleName,
  { eyebrow: string; title: string; description: string }
> = {
  Overview: {
    eyebrow: "Command center",
    title: "Operational overview",
    description: "Kondisi VPS, aplikasi, dan delivery dalam satu pandangan.",
  },
  Servers: {
    eyebrow: "Infrastructure",
    title: "Server resources",
    description:
      "CPU, memory, swap, disk, load, dan identitas host secara live.",
  },
  Services: {
    eyebrow: "Runtime",
    title: "Service health",
    description: "Status systemd dan hubungan setiap service dengan aplikasi.",
  },
  Projects: {
    eyebrow: "Inventory",
    title: "Project map",
    description: "Peta repo, domain, runtime, database, dan lokasi deployment.",
  },
  Docker: {
    eyebrow: "Containers",
    title: "Docker runtime",
    description:
      "Inventory container, image, port, status, dan akses log on demand.",
  },
  Logs: {
    eyebrow: "Observability",
    title: "Live log explorer",
    description:
      "Baca log yang diizinkan hanya ketika dibutuhkan, tanpa menyimpan secret.",
  },
  "CI/CD": {
    eyebrow: "GitHub delivery",
    title: "Repositories & Actions",
    description:
      "Repository dan workflow run dari cache MySQL, bukan hit GitHub per halaman.",
  },
  Deployments: {
    eyebrow: "Releases",
    title: "Deployment history",
    description:
      "Hubungkan commit, workflow, target runtime, dan health check.",
  },
  Alerts: {
    eyebrow: "Incident response",
    title: "Alerts & thresholds",
    description:
      "Risiko aktif, prioritas, sumber sinyal, dan langkah penanganan.",
  },
  Settings: {
    eyebrow: "Control plane",
    title: "Integrations & data policy",
    description:
      "Status koneksi, strategi sinkronisasi, retention, dan akses operator.",
  },
};

export const projects = [
  {
    id: "opsdeck",
    name: "Opsdeck",
    area: "Infrastructure",
    domain: "dev-ops.takahashiumaru.my.id",
    domains: ["dev-ops.takahashiumaru.my.id"],
    runtime: "Next.js 16 / Docker",
    repo: "takahashiumaru/dev-ops",
    target: "127.0.0.1:3000",
    path: "/home/ubuntu/dev-ops-dashboard",
    service: "dev-ops-dashboard.service",
    serviceScope: "system",
    database: "MySQL / Opsdeck",
    state: "online",
    commit: "managed",
    logStreams: ["app", "access", "error"],
  },
  {
    id: "fintrack",
    name: "Taka FinTrack",
    area: "Personal",
    domain: "takahashiumaru.my.id",
    domains: ["takahashiumaru.my.id"],
    runtime: "Next.js 14",
    repo: "takahashiumaru/taka-fintrack",
    target: "127.0.0.1:3001",
    path: "/home/ubuntu/taka-fintrack",
    service: "taka-fintrack.service",
    serviceScope: "user",
    database: "MySQL / taka_fintrack",
    state: "online",
    commit: "c8ba988a45",
    logStreams: ["app", "access", "error"],
  },
  {
    id: "aps-one",
    name: "APS One",
    area: "Freelance",
    domain: "apsone.web.id / apsone.app",
    domains: ["apsone.web.id", "apsone.app"],
    runtime: "Laravel / PHP 8.3",
    repo: "takahashiumaru/project-work-uaps",
    target: "Nginx → public",
    path: "/home/ubuntu/project-work-uaps",
    service: "nginx / php8.3-fpm",
    serviceScope: "system",
    database: "MySQL / aps",
    state: "degraded",
    commit: "5ac94f3d94",
    logStreams: ["app", "access", "error"],
  },
  {
    id: "sips",
    name: "SIPS Alhaq",
    area: "Freelance",
    domain: "sips-alhaq.studify.web.id / sips.takahashiumaru.my.id",
    domains: ["sips-alhaq.studify.web.id", "sips.takahashiumaru.my.id"],
    runtime: "Laravel / PHP 8.3",
    repo: "takahashiumaru/sips",
    target: "Nginx → public",
    path: "/home/ubuntu/sips",
    service: "nginx / php8.3-fpm",
    serviceScope: "system",
    database: "MySQL / sips",
    state: "degraded",
    commit: "ae1505b9f1",
    logStreams: ["app", "access", "error"],
  },
  {
    id: "onigiri",
    name: "Onigiri Shop",
    area: "Freelance",
    domain: "olshop-onigiri.studify.web.id",
    domains: ["olshop-onigiri.studify.web.id"],
    runtime: "Laravel / PHP 8.3",
    repo: "takahashiumaru/onigiri-online-shop",
    target: "Nginx → public",
    path: "/home/ubuntu/onigiri-online-shop",
    service: "nginx / php8.3-fpm",
    serviceScope: "system",
    database: "MySQL / onigiri_shop",
    state: "online",
    commit: "4d1340dbed",
    logStreams: ["app", "access", "error"],
  },
  {
    id: "router",
    name: "9Router",
    area: "Personal",
    domain: "takahashiumaru.web.id",
    domains: ["takahashiumaru.web.id"],
    runtime: "Next.js 16",
    repo: "9router-app package",
    target: "127.0.0.1:20128",
    path: "/home/ubuntu/.hermes/node/bin/9router",
    service: "9router.service",
    serviceScope: "user",
    database: "None mapped",
    state: "online",
    commit: "v0.5.20",
    logStreams: ["app", "access", "error"],
  },
  {
    id: "monitor",
    name: "VPS Monitoring",
    area: "Infrastructure",
    domain: "monitor.takahashiumaru.web.id",
    domains: ["monitor.takahashiumaru.web.id"],
    runtime: "Node.js",
    repo: "takahashiumaru/vps-monitoring",
    target: "127.0.0.1:3002",
    path: "/home/ubuntu/hermes-monitor",
    service: "server-monitoring.service",
    serviceScope: "user",
    database: "None",
    state: "online",
    commit: "d2bd4b8389",
    logStreams: ["app", "access", "error"],
  },
  {
    id: "hermes",
    name: "Hermes Dashboard",
    area: "Infrastructure",
    domain: "hermes.takahashiumaru.my.id",
    domains: ["hermes.takahashiumaru.my.id"],
    runtime: "Python / Hermes",
    repo: "Hermes installation",
    target: "127.0.0.1:9119",
    path: "/home/ubuntu/.hermes",
    service: "hermes-dashboard.service",
    serviceScope: "system",
    database: "Hermes runtime",
    state: "dns-missing",
    commit: "managed",
    logStreams: ["app", "access", "error"],
  },
  {
    id: "portfolio",
    name: "Umar Portfolio",
    area: "Freelance",
    domain: "portofolio.takahashiumaru.my.id",
    domains: ["portofolio.takahashiumaru.my.id"],
    runtime: "Static / Vite",
    repo: "Unmanaged directory",
    target: "Nginx static root",
    path: "/home/ubuntu/umar-portfolio/dist",
    service: "nginx",
    serviceScope: "system",
    database: "None",
    state: "online",
    commit: "unmanaged",
    logStreams: ["access", "error"],
  },

  {
    id: "umar-proxy",
    name: "Umar App Proxy",
    area: "Freelance",
    domain: "umarmarufmutaqin.my.id",
    domains: ["umarmarufmutaqin.my.id"],
    runtime: "Reverse proxy",
    repo: "Not linked",
    target: "127.0.0.1:3003",
    path: "No active runtime",
    service: "No listener",
    serviceScope: "system",
    database: "Unknown",
    state: "critical",
    commit: "unavailable",
    logStreams: ["access", "error"],
  },
] as const;

export const serviceInventory = [
  {
    name: "nginx",
    kind: "Reverse proxy",
    project: "All web apps",
    port: "80 / 443",
    action: "journalctl -u nginx",
  },
  {
    name: "php8.3-fpm",
    kind: "PHP runtime",
    project: "APS One / SIPS / Onigiri",
    port: "Unix socket",
    action: "journalctl -u php8.3-fpm",
  },
  {
    name: "mysql",
    kind: "Database",
    project: "Shared data layer",
    port: "3306 local",
    action: "journalctl -u mysql",
  },
  {
    name: "docker",
    kind: "Container engine",
    project: "Container workloads",
    port: "Local socket",
    action: "journalctl -u docker",
  },
  {
    name: "supervisor",
    kind: "Process manager",
    project: "Legacy workers",
    port: "-",
    action: "journalctl -u supervisor",
  },
  {
    name: "cron",
    kind: "Scheduler",
    project: "Server jobs",
    port: "-",
    action: "journalctl -u cron",
  },
  {
    name: "taka-fintrack.service",
    kind: "Node application",
    project: "Taka FinTrack",
    port: "3001",
    action: "journalctl --user",
  },
  {
    name: "9router.service",
    kind: "AI gateway",
    project: "9Router",
    port: "20128",
    action: "journalctl --user",
  },
  {
    name: "server-monitoring.service",
    kind: "Node monitoring app",
    project: "VPS Monitoring",
    port: "3002",
    action: "journalctl --user",
  },
  {
    name: "hermes-dashboard.service",
    kind: "Hermes dashboard",
    project: "Hermes Dashboard",
    port: "9119",
    action: "journalctl -u hermes-dashboard",
  },
  {
    name: "mnemosyne-dashboard.service",
    kind: "Memory dashboard",
    project: "Mnemosyne",
    port: "9121",
    action: "journalctl -u mnemosyne-dashboard",
  },
  {
    name: "hermes-gateway.service",
    kind: "Agent gateway",
    project: "Hermes runtime",
    port: "9120",
    action: "journalctl --user",
  },
  {
    name: "taka-school.service",
    kind: "Node application",
    project: "Taka School",
    port: "unknown",
    action: "journalctl --user",
  },
] as const;

export const alerts = [
  {
    severity: "warning" as "warning" | "critical",
    title: "Beberapa alias domain tidak memiliki DNS",
    source: "DNS inventory",
    age: "Live audit",
    detail:
      "apsone.app, hermes.takahashiumaru.my.id, sips.takahashiumaru.my.id, dan umarmarufmutaqin.my.id tidak resolve dari publik.",
  },
  {
    severity: "warning",
    title: "Taka School terus restart",
    source: "taka-school.service",
    age: "User systemd",
    detail:
      "Service terdeteksi dalam restart loop dan belum memiliki domain/runtime mapping yang stabil.",
  },
] as const;

export const deployments = [
  {
    project: "Opsdeck",
    environment: "production",
    method: "GitHub Actions → atomic Docker release",
    target: "dev-ops-dashboard.service",
    health: "HTTP + database",
    state: "ready" as "ready" | "mapped" | "blocked",
  },
  {
    project: "Taka FinTrack",
    environment: "production",
    method: "GitHub Actions → systemd",
    target: "taka-fintrack.service",
    health: "HTTP 200",
    state: "ready",
  },
  {
    project: "APS One",
    environment: "production",
    method: "Git pull → PHP-FPM",
    target: "/home/ubuntu/project-work-uaps",
    health: "Domain check",
    state: "mapped",
  },
  {
    project: "SIPS Alhaq",
    environment: "production",
    method: "Git pull → PHP-FPM",
    target: "/home/ubuntu/sips",
    health: "Domain check",
    state: "mapped",
  },
  {
    project: "Onigiri Shop",
    environment: "production",
    method: "Git pull → PHP-FPM",
    target: "/home/ubuntu/onigiri-online-shop",
    health: "Domain check",
    state: "mapped",
  },
  {
    project: "VPS Monitoring",
    environment: "production",
    method: "GitHub → user systemd",
    target: "server-monitoring.service",
    health: "HTTP 200",
    state: "ready",
  },
  {
    project: "Hermes Dashboard",
    environment: "production",
    method: "System service",
    target: "hermes-dashboard.service",
    health: "DNS missing",
    state: "mapped",
  },

] as const;

export const deliveryWorkflowRepositories = [
  "takahashiumaru/dev-ops",
  "takahashiumaru/taka-fintrack",
  "takahashiumaru/vps-monitoring",
] as const;
